### ISSUE TITLE
向量

### ISSUE THREAD

**Issue by YingXu-swim** [Sporot/TCM_NER#2]
hii！看到你的代码中：
    char_emb = "TCM_corpus/vec/char_200_em.txt"
    #char_emb = "data/gigaword_chn.all.a2b.uni.ite50.vec"
    bichar_emb = "TCM_corpus/vec/bichar_200_em.txt"
    #bichar_emb = "data/gigaword_chn.all.a2b.bi.ite50.vec"
    gaz_file = "TCM_corpus/vec/word_200_em.txt"
    #gaz_file = "data/ctb.50d.vec"

想知道能不能提供一下下TCM_corpus/vec下面的embedding vector 文件？
谢谢！

**Comment by Sporot** [comment]
你可以看一下我的另一个仓库，[TCM_word2vec](https://github.com/Sporot/TCM_word2vec)

里面提供了我训练的词向量文件
